const translations = {
  zh: {
    "brand.name": "天颐健康科技",
    "nav.about": "企业介绍",
    "nav.products": "产品矩阵",
    "nav.science": "科研实力",
    "nav.platform": "技术平台",
    "nav.solutions": "应用方案",
    "nav.cases": "市场案例",
    "hero.eyebrow": "天颐健康科技有限公司",
    "hero.title": "科技功能食品与生物制造解决方案平台",
    "hero.lead": "以药食同源功能原料为根基，融合高性能酶开发、微生态技术与应用验证能力",
    "hero.line": "藤茶 / 金花黑茶 / 青钱柳 / AKK 菌 / 高性能酶开发 / 生物制造",
    "hero.cta": "查看产品矩阵",
    "hero.cta2": "了解技术平台",
    "hero.stat1.sup": "+",
    "hero.stat1.label": "年科研积淀",
    "hero.stat2.label": "项发明专利",
    "hero.stat3.label": "技术平台协同",
    "about.kicker": "Company Focus",
    "about.title": "从功能原料到产业解决方案，构建健康产品创新平台",
    "about.desc": "天颐健康科技专注中国药食同源资源的现代化开发，并融合高性能酶开发、微生态技术、生物制造与应用验证能力，为功能食品、营养补充剂、农业、医药与工业客户提供从核心原料到产业化产品的一站式解决方案。",
    "about.stat1": "年科研积淀",
    "about.stat2": "发明专利",
    "about.stat3": "大核心赛道",
    "about.stat4": "应用场景",
    "about.unit1": "+",
    "about.unit2": "项",
    "about.unit3": "个",
    "science.kicker": "Science & Quality",
    "science.title": "用可验证数据与平台能力建立产业信任",
    "science.badge.label": "科研与生物技术平台",
    "science.intro": "每一项数据背后都是真实的临床试验、专利认证、科研机构背书与产业化验证路径，而非营销话术。",
    "science.num1": "11",
    "science.unit1": "项",
    "science.num2": "35",
    "science.unit2": "万+",
    "science.num3": "17",
    "science.unit3": "项",
    "science.num4": "400",
    "science.unit4": "+",
    "science.stat1": "发明专利与核心科研成果积累",
    "science.stat2": "AKK 菌株资源与菌种开发基础",
    "science.stat3": "AKK 相关专利认证",
    "science.stat4": "产品活性成分覆盖",
    "products.kicker": "Product Matrix",
    "products.title": "四大核心功能原料，支撑多场景健康产品创新",
    "products.direction": "核心方向",
    "products.card1.tag": "黄酮之王",
    "products.card1.title": "藤茶提取物",
    "products.card1.text": "来源于显齿蛇葡萄叶，核心成分二氢杨梅素 DMY，黄酮含量达 45%，可结合酶解、转化与配方适配拓展护肝、抗氧化和尿酸管理应用。",
    "products.card1.direction": "抗氧化、护肝解酒、尿酸管理、神经保护",
    "products.card2.tag": "黄金代谢因子",
    "products.card2.title": "金花黑茶提取物",
    "products.card2.text": "来源于安化黑茶，采用冠突散囊菌发酵技术，结合发酵与生物转化能力，面向靶向减脂、三高调理和肠道健康。",
    "products.card2.direction": "靶向减脂、三高调理、肠道健康",
    "products.card3.tag": "植物胰岛素",
    "products.card3.title": "青钱柳叶多酚",
    "products.card3.text": "核心成分为多酚与有机硒，多酚含量达 25%，可通过生物酶解和配方优化提升成分释放与应用稳定性。",
    "products.card3.direction": "血糖管理、血脂调节、胰岛保护",
    "products.card4.tag": "二代益生菌标杆",
    "products.card4.title": "AKM Lab-01 AKK 菌",
    "products.card4.text": "来源于慕恩生物，核心成分 Amuc_1100 蛋白，规格达万亿级 CFU，覆盖减重、抗衰、睡眠与免疫调节。",
    "products.card4.direction": "减重管理、抗衰老、睡眠、免疫调节",
    "experts.kicker": "Research Team",
    "experts.title": "科研团队与产学研平台",
    "experts.text": "由食品、生物信息学、茶叶深加工、微生态、酶工程及产业转化专家共同构成技术背书，联合科研机构与生物技术伙伴推动多学科交叉创新。",
    "experts.partners.label": "联合科研与技术伙伴",
    "experts.partner1": "中国工程院",
    "experts.partner2": "华南理工大学",
    "experts.partner3": "湖南农业大学",
    "experts.partner4": "慕恩生物",
    "experts.partner5": "美格基因",
    "experts.partner6": "智演生合",
    "experts.card1.title": "刘素纯教授",
    "experts.card1.text": "首席创始人科学家，国家规划教材《生物信息学》主编，具备科研与产业转化经验。",
    "experts.card2.title": "张友胜博士",
    "experts.card2.text": "中国藤茶现代化研究奠基人，为藤茶提取物研发提供关键技术支撑。",
    "solutions.kicker": "Application Solutions",
    "solutions.title": "多场景应用解决方案",
    "solutions.card1.title": "体重管理",
    "solutions.card1.text": "金花黑茶提取物与 AKK 菌协同，面向减少内脏脂肪与减重后管理。",
    "solutions.card2.title": "血糖管理",
    "solutions.card2.text": "青钱柳叶多酚实现糖脂双降，同时修复胰岛功能，助力血糖稳定。",
    "solutions.card3.title": "三高调理",
    "solutions.card3.text": "四大核心产品协同发力，改善血脂、血糖、胆固醇等代谢指标。",
    "solutions.card4.title": "护肝解酒",
    "solutions.card4.text": "藤茶提取物增强 ADH 与 ALDH 活性，加速酒精代谢。",
    "solutions.card5.title": "食品酶应用",
    "solutions.card5.text": "面向食品加工、植物蛋白改良、风味改善与功能成分释放，提供酶工程和生物转化方案。",
    "solutions.card6.title": "农业酶与饲料营养",
    "solutions.card6.text": "通过高性能酶与微生态技术，提升饲料利用效率、植物营养转化和农业资源循环水平。",
    "solutions.card7.title": "医药绿色合成",
    "solutions.card7.text": "面向药物中间体、蛋白改造和生物催化反应，提供可放大的酶开发支持。",
    "solutions.card8.title": "工业生物制造",
    "solutions.card8.text": "围绕洗涤酶、生物基化学品、绿色能源和工业处理场景，推动低碳高效制造。",
    "cases.kicker": "Market Proof",
    "cases.title": "从科研证据到市场产品，推动创新方案真实落地",
    "cases.card1.title": "北大医疗抗高血脂症临床",
    "cases.card1.text": "AKM Lab-01 AKK 菌开展抗高血脂症临床试验，试验编号 NCT06974266。",
    "cases.card2.title": "广州开发区医院减重临床",
    "cases.card2.text": "围绕 AKM Lab-01 AKK 菌开展减重临床试验，试验编号 NCT07331974。",
    "cases.card3.title": "青钱柳产品落地",
    "cases.card3.text": "应用于血糖管理类草本产品与成人乳粉，为糖脂管理配方提供差异化卖点。",
    "footer.tagline": "科技功能食品与生物制造解决方案平台",
    "footer.desc": "以药食同源功能原料为根基，融合高性能酶开发、微生态技术与应用验证能力，助力健康产品与生物制造项目落地。",
    "footer.title": "商务合作",
    "footer.role1": "国内负责人",
    "footer.role2": "国外负责人",
    "footer.name1": "王先生",
    "footer.name2": "胡先生",
    "footer.address": "地址",
    "footer.copyright": "© 2026 广州天颐健康科技有限公司. 保留所有权利.",
    "platform.kicker": "Technology Platform",
    "platform.title": "三大技术平台，打通从原料发现到产品转化的关键链路",
    "platform.intro": "从药食同源功能原料，到高性能酶开发，再到微生态与生物制造，天颐以多平台协同能力帮助客户降低研发风险、提升产品效率并加速商业化落地。",
    "platform.card1.title": "药食同源功能原料平台",
    "platform.card1.text": "基于中国药食同源资源，围绕活性成分筛选、功效机制研究、标准化提取、质量控制和应用配方开发，构建高活性功能原料产品体系。",
    "platform.card1.point1": "活性成分筛选",
    "platform.card1.point2": "标准化提取与质量控制",
    "platform.card1.point3": "配方应用适配",
    "platform.card2.title": "高性能酶开发平台",
    "platform.card2.text": "面向食品、农业、医药与工业应用，提供从候选酶筛选、酶分子优化、表达制备到应用验证的一站式开发服务。",
    "platform.card2.point1": "酶分子优化",
    "platform.card2.point2": "表达效率与制剂稳定性",
    "platform.card2.point3": "真实场景应用验证",
    "platform.card3.title": "微生态与生物制造平台",
    "platform.card3.text": "围绕菌株资源、发酵工艺、活性代谢物、生物转化和功能验证，推动微生态技术与健康产品、生物制造场景结合。",
    "platform.card3.point1": "菌株筛选与评价",
    "platform.card3.point2": "发酵与生物转化",
    "platform.card3.point3": "微生态功能验证",
    "enzyme.kicker": "Enzyme Development",
    "enzyme.title": "高性能酶开发与产品解决方案",
    "enzyme.text": "客户需要的往往不是单一酶产品，而是在真实配方、工艺和成本约束下可被验证的应用结果。天颐联合智演生合，围绕活性、稳定性、pH 适应性、底物谱、表达效率和制剂稳定性等关键指标，提供从候选酶筛选、分子优化、表达制备到应用验证的一站式解决方案。",
    "enzyme.step1.title": "明确应用目标",
    "enzyme.step1.text": "明确目标反应、底物、产物、配方环境、工艺条件和成本边界。",
    "enzyme.step2.title": "候选酶筛选",
    "enzyme.step2.text": "结合序列、结构、功能和数据库资源，筛选具备产业潜力的候选酶。",
    "enzyme.step3.title": "分子优化设计",
    "enzyme.step3.text": "围绕酶活、热稳定性、pH 适应性、底物谱和表达效率进行优化。",
    "enzyme.step4.title": "表达制备验证",
    "enzyme.step4.text": "建立表达体系和发酵制备路径，完成制剂稳定性与成本可行性验证。",
    "enzyme.step5.title": "应用场景验证",
    "enzyme.step5.text": "在食品、农业、医药或工业真实场景中验证实际效果和商业化可行性。"
  },
  en: {
    "brand.name": "Tianyi Health Tech",
    "nav.about": "About",
    "nav.products": "Products",
    "nav.science": "Science",
    "nav.platform": "Platform",
    "nav.solutions": "Solutions",
    "nav.cases": "Cases",
    "hero.eyebrow": "Tianyi Health Technology Co., Ltd.",
    "hero.title": "A Leader in Science-Backed Functional Food Ingredients",
    "hero.lead": "Functional ingredient solutions inspired by food-medicine homology",
    "hero.line": "Vine Tea / Golden Dark Tea / Cyclocarya paliurus / AKK",
    "hero.cta": "Explore Product Matrix",
    "hero.cta2": "About Us",
    "hero.stat1.sup": "+",
    "hero.stat1.label": "Years of R&D",
    "hero.stat2.label": "Invention Patents",
    "hero.stat3.label": "Core Ingredients",
    "about.kicker": "Company Focus",
    "about.title": "Addressing metabolic stress and sub-health challenges",
    "about.desc": "Tianyi Health Tech transforms Chinese food-medicine resources into high-activity functional ingredients for functional foods, supplements, and health management products.",
    "about.stat1": "Years of R&D",
    "about.stat2": "Invention Patents",
    "about.stat3": "Core Verticals",
    "about.stat4": "Application Scenarios",
    "about.unit1": "+",
    "about.unit2": "",
    "about.unit3": "",
    "science.kicker": "Science & Quality",
    "science.title": "Building ingredient trust through verifiable data",
    "science.badge.label": "National-Level Research Certification",
    "science.intro": "Every data point is backed by real clinical trials, patent certifications, and institutional endorsements — not marketing claims.",
    "science.num1": "11",
    "science.unit1": "",
    "science.num2": "350K+",
    "science.unit2": "",
    "science.num3": "17",
    "science.unit3": "",
    "science.num4": "400+",
    "science.unit4": "",
    "science.stat1": "invention patents and core research achievements",
    "science.stat2": "AKK strain resources and strain-development foundation",
    "science.stat3": "AKK-related patent certifications",
    "science.stat4": "active ingredient coverage across products",
    "products.kicker": "Product Matrix",
    "products.title": "Four Core Product Pillars",
    "products.direction": "Key Focus",
    "products.card1.tag": "King of Flavonoids",
    "products.card1.title": "Vine Tea Extract",
    "products.card1.text": "Derived from Ampelopsis grossedentata leaves, with DMY as the core active and 45% flavonoid content; qualified as a novel food ingredient.",
    "products.card1.direction": "Antioxidation, liver support, alcohol metabolism, uric acid management, neuroprotection",
    "products.card2.tag": "Golden Metabolic Factor",
    "products.card2.title": "Golden Dark Tea Extract",
    "products.card2.text": "Sourced from Anhua dark tea and developed with Eurotium cristatum fermentation technology for targeted fat reduction, metabolic balance, and gut health.",
    "products.card2.direction": "Targeted fat reduction, metabolic balance, gut health",
    "products.card3.tag": "Plant Insulin",
    "products.card3.title": "Cyclocarya paliurus Polyphenols",
    "products.card3.text": "Powered by polyphenols and organic selenium, with 25% polyphenol content for blood glucose, lipid management, and pancreatic function support.",
    "products.card3.direction": "Glucose management, lipid regulation, pancreatic protection",
    "products.card4.tag": "Next-Gen Probiotic Benchmark",
    "products.card4.title": "AKM Lab-01 AKK",
    "products.card4.text": "Sourced from MoonBio, featuring Amuc_1100 protein and trillion-level CFU specifications for weight management, healthy aging, sleep, and immune modulation.",
    "products.card4.direction": "Weight management, healthy aging, sleep, immune modulation",
    "experts.kicker": "Research Team",
    "experts.title": "Research team and industry-academia platform",
    "experts.text": "A multidisciplinary expert network spanning food science, bioinformatics, tea deep processing, and commercialization, connecting universities and research institutions.",
    "experts.partners.label": "Joint Research Institutions",
    "experts.partner1": "Chinese Academy of Engineering",
    "experts.partner2": "South China University of Technology",
    "experts.partner3": "Hunan Agricultural University",
    "experts.partner4": "MoonBio",
    "experts.partner5": "Meige Gene",
    "experts.card1.title": "Prof. Liu Suchun",
    "experts.card1.text": "Chief founding scientist and editor-in-chief of the national planning textbook Bioinformatics, with deep experience in research and commercialization.",
    "experts.card2.title": "Dr. Zhang Yousheng",
    "experts.card2.text": "A pioneer in modern vine tea research in China, providing key technical support for vine tea extract development.",
    "solutions.kicker": "Health Applications",
    "solutions.title": "Twelve Health Application Scenarios",
    "solutions.card1.title": "Weight Management",
    "solutions.card1.text": "Golden Dark Tea Extract and AKK work synergistically for visceral fat reduction and post-weight-loss management.",
    "solutions.card2.title": "Glucose Management",
    "solutions.card2.text": "Cyclocarya paliurus polyphenols support dual glucose-lipid management while helping maintain pancreatic function.",
    "solutions.card3.title": "Metabolic Balance",
    "solutions.card3.text": "The four core products work together to improve lipid, glucose, and cholesterol-related metabolic indicators.",
    "solutions.card4.title": "Liver & Alcohol Support",
    "solutions.card4.text": "Vine Tea Extract enhances ADH and ALDH activity to accelerate alcohol metabolism.",
    "solutions.card5.title": "Uric Acid Management",
    "solutions.card5.text": "Vine tea and golden dark tea provide dual mechanisms to inhibit uric acid formation and promote excretion.",
    "solutions.card6.title": "Healthy Aging",
    "solutions.card6.text": "AKK and Vine Tea Extract target oxidative stress, longevity pathways, and cognitive health.",
    "solutions.card7.title": "Sleep Support",
    "solutions.card7.text": "AKK modulates gut-brain axis signaling and supports 5-HT production for better sleep quality.",
    "solutions.card8.title": "Export-Ready Solutions",
    "solutions.card8.text": "The product line supports international compliance needs including FDA, GRAS, and TGA-oriented markets.",
    "cases.kicker": "Market Proof",
    "cases.title": "Application Cases & Partnership Directions",
    "cases.card1.title": "Peking University Medical Clinical Study",
    "cases.card1.text": "AKM Lab-01 AKK is under clinical evaluation for hyperlipidemia, trial ID NCT06974266.",
    "cases.card2.title": "Guangzhou Development District Hospital Study",
    "cases.card2.text": "AKM Lab-01 AKK is under clinical evaluation for weight management, trial ID NCT07331974.",
    "cases.card3.title": "Cyclocarya Product Applications",
    "cases.card3.text": "Applied in botanical products and adult milk powder for glucose management, enabling differentiated metabolic-health formulas.",
    "footer.tagline": "A Leader in Science-Backed Functional Food Ingredients",
    "footer.desc": "Dedicated to R&D and commercialization of food-medicine homology ingredients, empowering health product innovation through science.",
    "footer.title": "Business Partnership",
    "footer.role1": "Domestic Director",
    "footer.role2": "International Director",
    "footer.name1": "Mr. Wang",
    "footer.name2": "Mr. Hu",
    "footer.address": "Address",
    "footer.copyright": "© 2026 Guangzhou Tianyi Health Technology Co., Ltd. All rights reserved.",
    "platform.kicker": "Technology Platform",
    "platform.title": "Three technology platforms connecting ingredient discovery to product commercialization",
    "platform.intro": "From food-medicine homology ingredients to high-performance enzyme development and microbiome-enabled biomanufacturing, Tianyi helps clients reduce R&D risk, improve product efficiency, and accelerate commercialization.",
    "platform.card1.title": "Food-Medicine Homology Ingredient Platform",
    "platform.card1.text": "Built on Chinese botanical resources, this platform integrates active screening, mechanism research, standardized extraction, quality control, and formulation application.",
    "platform.card1.point1": "Active screening",
    "platform.card1.point2": "Standardized extraction & QC",
    "platform.card1.point3": "Formulation adaptation",
    "platform.card2.title": "High-Performance Enzyme Development Platform",
    "platform.card2.text": "For food, agriculture, pharma, and industrial applications, we provide candidate screening, enzyme optimization, expression, preparation, and application validation.",
    "platform.card2.point1": "Enzyme optimization",
    "platform.card2.point2": "Expression & formulation stability",
    "platform.card2.point3": "Real-scenario validation",
    "platform.card3.title": "Microbiome & Biomanufacturing Platform",
    "platform.card3.text": "Centered on strain resources, fermentation, active metabolites, biotransformation, and functional validation, this platform connects microbiome technologies with product innovation.",
    "platform.card3.point1": "Strain screening",
    "platform.card3.point2": "Fermentation & biotransformation",
    "platform.card3.point3": "Microbiome validation",
    "enzyme.kicker": "Enzyme Development",
    "enzyme.title": "High-Performance Enzyme Development & Product Solutions",
    "enzyme.text": "Clients often need more than a single enzyme product — they need validated outcomes under real formulation, process, and cost constraints. Together with Aivolution, Tianyi provides end-to-end solutions from candidate screening and molecular optimization to expression, preparation, and application validation.",
    "enzyme.step1.title": "Define Application Goals",
    "enzyme.step1.text": "Clarify target reactions, substrates, products, formulation conditions, processes, and cost boundaries.",
    "enzyme.step2.title": "Screen Candidate Enzymes",
    "enzyme.step2.text": "Identify promising enzymes through sequence, structure, function, and database resources.",
    "enzyme.step3.title": "Optimize Enzyme Design",
    "enzyme.step3.text": "Optimize activity, thermal stability, pH adaptability, substrate scope, and expression efficiency.",
    "enzyme.step4.title": "Validate Expression & Preparation",
    "enzyme.step4.text": "Build expression and fermentation routes while validating formulation stability and cost feasibility.",
    "enzyme.step5.title": "Validate Application Scenarios",
    "enzyme.step5.text": "Test real-world performance and commercialization feasibility in food, agriculture, pharma, or industrial scenarios."
  }
};

const langToggle = document.querySelector("[data-lang-toggle]");
const i18nNodes = document.querySelectorAll("[data-i18n]");

function applyLanguage(lang) {
  const language = translations[lang] ? lang : "zh";
  document.documentElement.lang = language === "zh" ? "zh-CN" : "en";
  document.body.dataset.lang = language;
  i18nNodes.forEach((node) => {
    const key = node.dataset.i18n;
    const val = translations[language][key];
    if (val !== undefined) node.textContent = val;
  });
  if (langToggle) langToggle.textContent = language === "zh" ? "EN" : "中";
}

// ── IP-based auto language detection ──
const params = new URLSearchParams(window.location.search);

// Priority: URL param > localStorage manual choice > IP detection > fallback zh
function initLanguage() {
  const urlLang = params.get("lang");
  if (urlLang) {
    applyLanguage(urlLang);
    return;
  }

  const stored = localStorage.getItem("ty-lang");
  if (stored) {
    applyLanguage(stored);
    return;
  }

  // IP-based detection
  fetch("https://ipapi.co/json/")
    .then(res => res.json())
    .then(data => {
      const lang = data.country_code === "CN" ? "zh" : "en";
      applyLanguage(lang);
    })
    .catch(() => {
      // fallback to browser language
      const browserLang = navigator.language || navigator.languages[0];
      applyLanguage(browserLang.startsWith("zh") ? "zh" : "en");
    });
}

initLanguage();

if (langToggle) {
  langToggle.addEventListener("click", () => {
    const next = document.body.dataset.lang === "zh" ? "en" : "zh";
    localStorage.setItem("ty-lang", next); // remember user choice
    applyLanguage(next);
  });
}
