const translations = {
  zh: {
    "brand.name": "天颐健康科技",
    "nav.products": "产品矩阵",
    "nav.science": "科研实力",
    "nav.solutions": "应用方案",
    "nav.cases": "市场案例",
    "theme.green": "科技绿版",
    "theme.gold": "草本金版",
    "hero.eyebrow": "天颐健康科技有限公司",
    "hero.title": "科技功能食品产业领导者",
    "hero.lead": "药食同源功能原料解决方案",
    "hero.line": "藤茶 / 金花黑茶 / 青钱柳 / AKK 菌",
    "hero.cta": "查看产品矩阵",
    "intro.kicker": "Company Focus",
    "intro.title": "面向现代人的代谢危机与亚健康困扰",
    "intro.card1.title": "企业核心定位",
    "intro.card1.text": "专注将中国药食同源资源转化为高活性功能性原料，服务功能食品、营养补充剂与健康管理产品创新。",
    "intro.card2.title": "科研实力依托",
    "intro.card2.text": "依托刘仲华院士团队长达 20 年科研积淀，联合华南理工大学、湖南农业大学等机构协同研发。",
    "intro.card3.title": "业务模式构成",
    "intro.card3.text": "采用自主研发、战略投资、独家代理结合的模式，布局代谢健康、肠道健康、抗衰老等核心赛道。",
    "science.kicker": "Science & Quality",
    "science.title": "用可验证数据建立原料信任",
    "science.num1": "11 项",
    "science.num2": "35 万+",
    "science.num3": "17 项",
    "science.num4": "400+",
    "science.stat1": "发明专利与核心科研成果积累",
    "science.stat2": "AKK 菌株资源与菌种开发基础",
    "science.stat3": "AKK 相关专利认证",
    "science.stat4": "产品活性成分覆盖",
    "products.kicker": "Product Matrix",
    "products.title": "四大核心产品矩阵",
    "products.direction": "核心方向",
    "products.card1.tag": "黄酮之王",
    "products.card1.title": "藤茶提取物",
    "products.card1.text": "来源于显齿蛇葡萄叶，核心成分二氢杨梅素 DMY，黄酮含量达 45%，具备新食品原料资质。",
    "products.card1.direction": "抗氧化、护肝解酒、尿酸管理、神经保护",
    "products.card2.tag": "黄金代谢因子",
    "products.card2.title": "金花黑茶提取物",
    "products.card2.text": "来源于安化黑茶，采用冠突散囊菌发酵技术，面向靶向减脂、三高调理和肠道健康。",
    "products.card3.tag": "植物胰岛素",
    "products.card3.title": "青钱柳叶多酚",
    "products.card3.text": "核心成分为多酚与有机硒，多酚含量达 25%，用于血糖管理、血脂调节与胰岛功能保护。",
    "products.card4.tag": "二代益生菌标杆",
    "products.card4.title": "AKM Lab-01 AKK 菌",
    "products.card4.text": "来源于慕恩生物，核心成分 Amuc_1100 蛋白，规格达万亿级 CFU，覆盖减重、抗衰、睡眠与免疫调节。",
    "experts.kicker": "Research Team",
    "experts.title": "科研团队与产学研平台",
    "experts.text": "由食品、生物信息学、茶叶深加工及产业转化专家共同构成技术背书，联合多所高校与科研机构推动多学科交叉创新。",
    "experts.card1.title": "刘素纯教授",
    "experts.card1.text": "首席创始人科学家，国家规划教材《生物信息学》主编，具备科研与产业转化经验。",
    "experts.card2.title": "张友胜博士",
    "experts.card2.text": "中国藤茶现代化研究奠基人，为藤茶提取物研发提供关键技术支撑。",
    "experts.card3.title": "刘仲华院士",
    "experts.card3.text": "中国工程院院士，国家科技进步二等奖获得者，为公司提供核心技术指导与战略支持。",
    "solutions.kicker": "Health Applications",
    "solutions.title": "十二大健康应用场景",
    "solutions.card1.title": "体重管理",
    "solutions.card1.text": "金花黑茶提取物与 AKK 菌协同，面向减少内脏脂肪与减重后管理。",
    "solutions.card2.title": "血糖管理",
    "solutions.card2.text": "青钱柳叶多酚实现糖脂双降，同时修复胰岛功能，助力血糖稳定。",
    "solutions.card3.title": "三高调理",
    "solutions.card3.text": "四大核心产品协同发力，改善血脂、血糖、胆固醇等代谢指标。",
    "solutions.card4.title": "护肝解酒",
    "solutions.card4.text": "藤茶提取物增强 ADH 与 ALDH 活性，加速酒精代谢。",
    "solutions.card5.title": "尿酸管理",
    "solutions.card5.text": "藤茶与金花黑茶双机制作用，抑制尿酸生成并促进排泄。",
    "solutions.card6.title": "深度抗衰",
    "solutions.card6.text": "AKK 菌与藤茶提取物搭配，面向氧化应激、寿命与认知健康。",
    "solutions.card7.title": "睡眠改善",
    "solutions.card7.text": "AKK 菌调节脑-肠轴信号，增加 5-HT 产生，支持睡眠质量提升。",
    "solutions.card8.title": "出口方案",
    "solutions.card8.text": "产品线覆盖 FDA、GRAS、TGA 等国际市场合规需求。",
    "cases.kicker": "Market Proof",
    "cases.title": "应用案例与合作方向",
    "cases.card1.title": "北大医疗抗高血脂症临床",
    "cases.card1.text": "AKM Lab-01 AKK 菌开展抗高血脂症临床试验，试验编号 NCT06974266。",
    "cases.card2.title": "广州开发区医院减重临床",
    "cases.card2.text": "围绕 AKM Lab-01 AKK 菌开展减重临床试验，试验编号 NCT07331974。",
    "cases.card3.title": "青钱柳产品落地",
    "cases.card3.text": "应用于血糖管理类草本产品与成人乳粉，为糖脂管理配方提供差异化卖点。"
  },
  en: {
    "brand.name": "Tianyi Health Tech",
    "nav.products": "Products",
    "nav.science": "Science",
    "nav.solutions": "Solutions",
    "nav.cases": "Cases",
    "theme.green": "Tech Green",
    "theme.gold": "Herbal Gold",
    "hero.eyebrow": "Tianyi Health Technology Co., Ltd.",
    "hero.title": "A Leader in Science-Backed Functional Food Ingredients",
    "hero.lead": "Functional ingredient solutions inspired by food-medicine homology",
    "hero.line": "Vine Tea / Golden Dark Tea / Cyclocarya paliurus / AKK",
    "hero.cta": "Explore Product Matrix",
    "intro.kicker": "Company Focus",
    "intro.title": "Addressing metabolic stress and sub-health challenges",
    "intro.card1.title": "Core Positioning",
    "intro.card1.text": "We transform Chinese food-medicine resources into high-activity functional ingredients for functional foods, supplements, and health management products.",
    "intro.card2.title": "Research Foundation",
    "intro.card2.text": "Built on two decades of research from Academician Liu Zhonghua’s team, with joint R&D across South China University of Technology, Hunan Agricultural University, and more.",
    "intro.card3.title": "Business Model",
    "intro.card3.text": "Our portfolio combines self-developed technologies, strategic investment, and exclusive agency partnerships across metabolic health, gut health, and healthy aging.",
    "science.kicker": "Science & Quality",
    "science.title": "Building ingredient trust through verifiable data",
    "science.num1": "11",
    "science.num2": "350K+",
    "science.num3": "17",
    "science.num4": "400+",
    "science.stat1": "invention patents and core research achievements",
    "science.stat2": "AKK strain resources and strain-development foundation",
    "science.stat3": "AKK-related patent certifications",
    "science.stat4": "active ingredient coverage across products",
    "products.kicker": "Product Matrix",
    "products.title": "Four Core Product Pillars",
    "products.direction": "Key Focus",
    "products.card1.tag": "King of Flavonoids",
    "products.card1.title": "Vine Tea Extract",
    "products.card1.text": "Derived from Ampelopsis grossedentata leaves, with DMY as the core active and 45% flavonoid content; qualified as a novel food ingredient.",
    "products.card1.direction": "Antioxidation, liver support, alcohol metabolism, uric acid management, neuroprotection",
    "products.card2.tag": "Golden Metabolic Factor",
    "products.card2.title": "Golden Dark Tea Extract",
    "products.card2.text": "Sourced from Anhua dark tea and developed with Eurotium cristatum fermentation technology for targeted fat reduction, metabolic balance, and gut health.",
    "products.card3.tag": "Plant Insulin",
    "products.card3.title": "Cyclocarya paliurus Polyphenols",
    "products.card3.text": "Powered by polyphenols and organic selenium, with 25% polyphenol content for blood glucose, lipid management, and pancreatic function support.",
    "products.card4.tag": "Next-Gen Probiotic Benchmark",
    "products.card4.title": "AKM Lab-01 AKK",
    "products.card4.text": "Sourced from MoonBio, featuring Amuc_1100 protein and trillion-level CFU specifications for weight management, healthy aging, sleep, and immune modulation.",
    "experts.kicker": "Research Team",
    "experts.title": "Research team and industry-academia platform",
    "experts.text": "A multidisciplinary expert network spanning food science, bioinformatics, tea deep processing, and commercialization, connecting universities and research institutions.",
    "experts.card1.title": "Prof. Liu Suchun",
    "experts.card1.text": "Chief founding scientist and editor-in-chief of the national planning textbook Bioinformatics, with deep experience in research and commercialization.",
    "experts.card2.title": "Dr. Zhang Yousheng",
    "experts.card2.text": "A pioneer in modern vine tea research in China, providing key technical support for vine tea extract development.",
    "experts.card3.title": "Academician Liu Zhonghua",
    "experts.card3.text": "Academician of the Chinese Academy of Engineering and National Science and Technology Progress Award winner, providing strategic and technical guidance.",
    "solutions.kicker": "Health Applications",
    "solutions.title": "Twelve Health Application Scenarios",
    "solutions.card1.title": "Weight Management",
    "solutions.card1.text": "Golden Dark Tea Extract and AKK work synergistically for visceral fat reduction and post-weight-loss management.",
    "solutions.card2.title": "Glucose Management",
    "solutions.card2.text": "Cyclocarya paliurus polyphenols support dual glucose-lipid management while helping maintain pancreatic function.",
    "solutions.card3.title": "Metabolic Balance",
    "solutions.card3.text": "The four core products work together to improve lipid, glucose, and cholesterol-related metabolic indicators.",
    "solutions.card4.title": "Liver & Alcohol Support",
    "solutions.card4.text": "Vine Tea Extract enhances ADH and ALDH activity to accelerate alcohol metabolism.",
    "solutions.card5.title": "Uric Acid Management",
    "solutions.card5.text": "Vine tea and golden dark tea provide dual mechanisms to inhibit uric acid formation and promote excretion.",
    "solutions.card6.title": "Healthy Aging",
    "solutions.card6.text": "AKK and Vine Tea Extract target oxidative stress, longevity pathways, and cognitive health.",
    "solutions.card7.title": "Sleep Support",
    "solutions.card7.text": "AKK modulates gut-brain axis signaling and supports 5-HT production for better sleep quality.",
    "solutions.card8.title": "Export-Ready Solutions",
    "solutions.card8.text": "The product line supports international compliance needs including FDA, GRAS, and TGA-oriented markets.",
    "cases.kicker": "Market Proof",
    "cases.title": "Application Cases & Partnership Directions",
    "cases.card1.title": "Peking University Medical Clinical Study",
    "cases.card1.text": "AKM Lab-01 AKK is under clinical evaluation for hyperlipidemia, trial ID NCT06974266.",
    "cases.card2.title": "Guangzhou Development District Hospital Study",
    "cases.card2.text": "AKM Lab-01 AKK is under clinical evaluation for weight management, trial ID NCT07331974.",
    "cases.card3.title": "Cyclocarya Product Applications",
    "cases.card3.text": "Applied in botanical products and adult milk powder for glucose management, enabling differentiated metabolic-health formulas."
  }
};

const langToggle = document.querySelector("[data-lang-toggle]");
const i18nNodes = document.querySelectorAll("[data-i18n]");

function applyLanguage(lang) {
  const language = translations[lang] ? lang : "zh";
  document.documentElement.lang = language === "zh" ? "zh-CN" : "en";
  document.body.dataset.lang = language;
  i18nNodes.forEach((node) => {
    const key = node.dataset.i18n;
    if (translations[language][key]) node.textContent = translations[language][key];
  });
  if (langToggle) langToggle.textContent = language === "zh" ? "EN" : "中";
}

const params = new URLSearchParams(window.location.search);
applyLanguage(params.get("lang") || "zh");

if (langToggle) {
  langToggle.addEventListener("click", () => {
    applyLanguage(document.body.dataset.lang === "zh" ? "en" : "zh");
  });
}
